import type { ScrollScrubScene, ScrollScrubTheme } from "@/components/scroll-scrub/scroll-scrub";

export const scrollScrubTheme: ScrollScrubTheme = {
  accent: "#EE5B78",
  background: "#131B37",
  ink: "#F5F3EE",
  muted: "#B6BDD1",
};

export const scrollScrubScenes: ScrollScrubScene[] = [
  {
    id: "scene-01",
    label: "01 / Piano",
    clip: "/assets/world/scene-01.mp4",
    mobileClip: "/assets/world/scene-01-mobile.mp4",
    poster: "/assets/world/scene-01-poster.webp",
    mobilePoster: "/assets/world/scene-01-mobile-poster.webp",
    title: "Ike Machover",
    body: "The first notes, somewhere wide open.",
    kicker: "Where it begins",
    align: "left",
    scroll: 1.25,
  },
  {
    id: "scene-02",
    label: "02 / Wedding",
    clip: "/assets/world/scene-02.mp4?v=hd-20261006",
    mobileClip: "/assets/world/scene-02-mobile.mp4?v=hd-20261006",
    poster: "/assets/world/scene-02-poster.webp?v=hd-20261006",
    mobilePoster: "/assets/world/scene-02-mobile-poster.webp?v=hd-20261006",
    title: "Ike Machover",
    body: "A celebration of rhythm, family, and worlds meeting.",
    align: "right",
    scroll: 1.25,
  },
  {
    id: "scene-03",
    label: "03 / Gaming",
    clip: "/assets/world/scene-03.mp4?v=hd-20261006",
    mobileClip: "/assets/world/scene-03-mobile.mp4?v=hd-20261006",
    poster: "/assets/world/scene-03-poster.webp?v=hd-20261006",
    mobilePoster: "/assets/world/scene-03-mobile-poster.webp?v=hd-20261006",
    title: "Ike Machover",
    body: "After-school worlds and endless possibility.",
    align: "left",
    scroll: 1.25,
  },
  {
    id: "scene-04",
    label: "04 / Hockey",
    clip: "/assets/world/scene-04.mp4",
    mobileClip: "/assets/world/scene-04-mobile.mp4",
    poster: "/assets/world/scene-04-poster.webp",
    mobilePoster: "/assets/world/scene-04-mobile-poster.webp",
    title: "Ike Machover",
    body: "Speed, precision, and the joy of the game.",
    kicker: "The rush",
    align: "left",
    scroll: 1.25,
  },
  {
    id: "scene-05",
    label: "05 / Florida",
    clip: "/assets/world/scene-05.mp4",
    mobileClip: "/assets/world/scene-05-mobile.mp4",
    poster: "/assets/world/scene-05-poster.webp",
    mobilePoster: "/assets/world/scene-05-mobile-poster.webp",
    title: "Ike Machover",
    body: "Following the wild path south.",
    align: "right",
    scroll: 1.25,
  },
  {
    id: "scene-06",
    label: "06 / Ocean",
    clip: "/assets/world/scene-06.mp4",
    mobileClip: "/assets/world/scene-06-mobile.mp4",
    poster: "/assets/world/scene-06-poster.webp",
    mobilePoster: "/assets/world/scene-06-mobile-poster.webp",
    title: "Ike Machover",
    body: "Another universe just beneath the surface.",
    align: "left",
    scroll: 1.25,
  },
  {
    id: "scene-07",
    label: "07 / Mountains",
    clip: "/assets/world/scene-07.mp4",
    mobileClip: "/assets/world/scene-07-mobile.mp4",
    poster: "/assets/world/scene-07-poster.webp",
    mobilePoster: "/assets/world/scene-07-mobile-poster.webp",
    title: "Ike Machover",
    body: "Gravity becomes a game.",
    align: "right",
    scroll: 1.25,
  },
  {
    id: "scene-08",
    label: "08 / Coding",
    clip: "/assets/world/scene-08.mp4",
    mobileClip: "/assets/world/scene-08-mobile.mp4",
    poster: "/assets/world/scene-08-poster.webp",
    mobilePoster: "/assets/world/scene-08-mobile-poster.webp",
    title: "Ike Machover",
    body: "Curiosity turns into code.",
    align: "left",
    scroll: 1.25,
  },
  {
    id: "scene-09",
    label: "09 / Hardware",
    clip: "/assets/world/scene-09.mp4",
    mobileClip: "/assets/world/scene-09-mobile.mp4",
    poster: "/assets/world/scene-09-poster.webp",
    mobilePoster: "/assets/world/scene-09-mobile-poster.webp",
    title: "Ike Machover",
    body: "Building computers and crypto rigs, part by part.",
    kicker: "Build it",
    align: "right",
    scroll: 1.25,
  },
  {
    id: "scene-10",
    label: "10 / AI Build",
    clip: "/assets/world/scene-10.mp4",
    mobileClip: "/assets/world/scene-10-mobile.mp4",
    poster: "/assets/world/scene-10-poster.webp",
    mobilePoster: "/assets/world/scene-10-mobile-poster.webp",
    title: "Ike Machover",
    body: "Programming the rig with AI as a new collaborator.",
    kicker: "Think / make / repeat",
    align: "left",
    scroll: 1.25,
  },
  {
    id: "scene-11",
    label: "11 / Universe",
    clip: "/assets/world/scene-11.mp4",
    mobileClip: "/assets/world/scene-11-mobile.mp4",
    poster: "/assets/world/scene-11-poster.webp",
    mobilePoster: "/assets/world/scene-11-mobile-poster.webp",
    title: "Ike Machover",
    body: "The questions keep getting bigger.",
    kicker: "Beyond the horizon",
    align: "left",
    scroll: 1.5,
  },
];
